=== GitHubRepoForGTS/RepoForLSRFeed/LSR Feed/src/file_io/dtd/LSRExtract.dtd
<!-- DTD (Document Type Definition) file to validate LSRExtract report.xml -->

<!-- used in these Lenovo business lines:				-->

<!--     break-fix			(bf)				-->

<!--     depot repair			(dr)				-->

<!--	 install			(ins)				-->

<!--	 parts logistics 		(pl)				-->

<!--	 remote customer support 	(rcs)				-->



<!-- Modification History                                              	-->

<!-- 01/09/2005 | KW | First Cut					-->

<!-- 06/20/2006 | VM | Added a new multi report node which can contain  -->

<!--                   one or more sub reports.                         -->
<1-- 07/06/2012 | MM | Added attribute delimiter for fileName           -->




<!-- reports element: contains >=1 report or multiReport elements -->

<!ELEMENT reports ((report | multiReport)+)>



	<!-- dateFormat, timeFormat can appear at most once, if at all, in the report element. -->

	<!--   if dateFormat is not specified, it will be defaulted to YYYYMMDD                -->

	<!--   if timeFormat is not specified, it will be defaulted to hh:mm:ss                -->

	<!-- fileName, SQL must appear once in report element.                                 --> 

	<!ELEMENT report (fileType?,fileName,dateFormat?,timeFormat?,SQL) >

		<!-- includeHeader attribute specifies the format of header record, if one is wanted at all -->

		<!-- Custom: *HDR nnnnnn fileNameText_yyyymmdd.csv yyyymmdd 	-->

		<!-- Db2Header: Db2 column names 				-->

		<!ATTLIST report includeHeader (Custom | Db2Header | None) #IMPLIED>

	<!ELEMENT multiReport (fileType?,fileName,dateFormat?,timeFormat?,subReport+) >
		<!ELEMENT fileType EMPTY > 
			<!ATTLIST fileType text (csv|xls) "csv">
      		<!ATTLIST fileType title CDATA #IMPLIED>
		<!ELEMENT fileName EMPTY > 
			<!ATTLIST fileName text CDATA #REQUIRED >
			<!ATTLIST fileName delimiter CDATA #IMPLIED >
		<!ELEMENT dateFormat EMPTY > 
			<!ATTLIST dateFormat text CDATA #IMPLIED >
		<!ELEMENT timeFormat EMPTY > 
			<!ATTLIST timeFormat text CDATA #IMPLIED >
		<!ELEMENT SQL EMPTY >
			<!ATTLIST SQL text CDATA #REQUIRED >
		<!ELEMENT subReport (SQL)>
			<!-- includeHeader attribute specifies the format of header record, if one is wanted at all -->
			<!-- Db2Header: Db2 column names or None 				-->
			<!ATTLIST subReport includeHeader (Db2Header | None) #IMPLIED>
			<!-- includeTotals attribute specifies numeric columns should have the total generated -->
			<!ATTLIST subReport includeTotals (Y | y | N | n) #IMPLIED>

=== GitHubRepoForGTS/RepoForLSRFeed/LSR Feed/src/file_io/lsr_extract/xml_reports/invoices.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--                                                 -->
<!--    Break-fix - Report SQLs DTD and XML          -->
<!--                                                 -->

<!-- Modification History                            	 		-->
<!-- 01/06/2005 | KW | First Cut					-->
<!-- 01/09/2005 | KW | Moved DTD to external file LSRExtract.dtd	-->
<!-- 03/28/2006 | VM | C2246 Changed SQl for each report to add new columns             -->
<!--                   C2246 Changed the export file name for all reports               -->
<!--                   C2246 Changed the date format for all reports                    -->


<!DOCTYPE reports SYSTEM "./../../dtd/LSRExtract.dtd">

<reports>

  <!-- Bill to Lenovo (includes new and resubmitted transactions -->

  <report includeHeader="Custom">
    <fileName text="onsitebfservice_CA.csv" />
    <dateFormat text="YYYYMMDD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
	SELECT 	MACH,SERIAL,LLI,PERIOD_END_DTE,SERVICE_DTE,DOCNUM,ECA,POSTAL_CDE,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,'' AS LENOVO_KEY,TRANSACTION_ID,HOURS,COMPANY_NAME,CUSTOMER_PHONE,ADDRESS_FLOOR,ADDRESS_STREET,DISTRICT,CITY,STATE,CLAIM_NUMBER
	FROM LENOVO.BF_BILLABLE_V 
	WHERE PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE - 1 MONTH) AND MONTH = MONTH(CURRENT DATE - 1 MONTH))
    " />
  </report>

  <report includeHeader="Custom">
    <fileName text="depotrepair_CA.csv" />
    <dateFormat text="YYYYMMDD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
	SELECT 	MACH,SERIAL,LLI,PERIOD_END_DTE,DOCNUM,ECA,POSTAL_CDE,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,'' AS LENOVO_KEY,TRANSACTION_ID,HOURS,COMPANY_NAME,CUSTOMER_PHONE,ADDRESS_FLOOR,ADDRESS_STREET,DISTRICT,CITY,STATE,CLAIM_NUMBER
	FROM LENOVO.DR_BILLABLE_V 
	WHERE PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE - 1 MONTH) AND MONTH = MONTH(CURRENT DATE - 1 MONTH))
    " />
  </report>

  <report includeHeader="Custom">
    <fileName text="installation_CA.csv" />
    <dateFormat text="YYYYMMDD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
    	SELECT 	MACH,SERIAL,LLI,PERIOD_END_DTE,SERVICE_DTE,DOCNUM,POSTAL_CDE,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,'' AS LENOVO_KEY,TRANSACTION_ID,COMPANY_NAME,CUSTOMER_PHONE,ADDRESS_FLOOR,ADDRESS_STREET,DISTRICT,CITY,STATE,CLAIM_NUMBER
    	FROM LENOVO.INS_BILLABLE_V 
    	WHERE PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE - 1 MONTH) AND MONTH = MONTH(CURRENT DATE - 1 MONTH))
    " />
  </report>

  <report includeHeader="Custom">
    <fileName text="partslogistics_CA.csv" />
    <dateFormat text="YYYYMMDD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
    	SELECT 	MACH,LLI,PERIOD_END_DTE,SHIP_DTE,DOCNUM,CLAIM_NUM,PARTNO,PARTQTY,PART_COST,DIST_COST,PART_CREDIT,POSTAL_CDE,ORDER_NUM,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,'' AS LENOVO_KEY,TRANSACTION_ID,SERIAL,COMPANY_NAME,CUSTOMER_PHONE,ADDRESS_FLOOR,ADDRESS_STREET,DISTRICT,CITY,STATE
    	FROM LENOVO.PL_BILLABLE_V 
    	WHERE PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE - 1 MONTH) AND MONTH = MONTH(CURRENT DATE - 1 MONTH))
    " />
  </report>

  <report includeHeader="Custom">
    <fileName text="remotecustsupport_CA.csv" />
    <dateFormat text="YYYYMMDD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
	SELECT 	MACH,SERIAL,LLI,PERIOD_END_DTE,DOCNUM,POSTAL_CDE,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,'' AS LENOVO_KEY,TRANSACTION_ID,COMPANY_NAME,CUSTOMER_PHONE,ADDRESS_FLOOR,ADDRESS_STREET,DISTRICT,CITY,STATE,BRAND,RCS_CATEGORY,CLAIM_NUMBER
	FROM LENOVO.RCS_BILLABLE_V 
	WHERE PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE - 1 MONTH) AND MONTH = MONTH(CURRENT DATE - 1 MONTH))
    " />
  </report>

</reports>

=== GitHubRepoForGTS/RepoForLSRFeed/LSR Feed/src/file_io/lsr_extract/xml_reports/accrual.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--                                                 -->
<!--    Break-fix - Report SQLs DTD and XML          -->
<!--                                                 -->

<!-- Modification History                            	 		-->
<!-- 01/06/2005 | KW | First Cut					-->
<!-- 01/09/2005 | KW | Moved DTD to external file LSRExtract.dtd	-->
<!-- 03/28/2006 | VM | C2246 Changed SQl for each report to add new columns             -->
<!--                   C2246 Changed the export file name for all reports               -->
<!--                   C2246 Changed the date format for all reports                    -->
<!-- 2009-04-27 | VM | Added ISC fee for IBM reporting on Royal Bank Activity           -->
<!-- 2009-05-01 | VM | Added capability to accommodate a parts management fee credit     -->
<!-- 2009-06-29 | VM | V18 Change the capture period to use min LEN_DATA_REC column = N -->
<!-- 2009-12-01 | VM | Added section for PARTS_COST_CR -->
<!-- 2010-04-01 | VM | Modified where clause from selecing only New and Resubmit to include all records that have not been cancelled. -->
<!-- 2010-05-26 | VM | Modified Parts Management Fee from 9 percent to 7 percent -->
<!-- 2011-01-20 | VM | Modified Parts Management Fee from 7 percent to 2.3 percent -->


<!DOCTYPE reports SYSTEM "./../../dtd/LSRExtract.dtd">

<reports>
 
  <multiReport>
      <fileName text="lenovo_accrual.csv" />
      <dateFormat text="MMMM dd yyyy" />
      <timeFormat text="HH:MM:SS" />

      <subReport includeHeader="None" includeTotals="N">
      	<SQL text="
      	
		SELECT
		'LENOVO ACCRUAL PERIOD ENDING '  || CAST (MIN(PERIOD_END_DTE) AS CHAR(10))
		FROM LENOVO.PERIOD_DATES WHERE LEN_DATA_REC = 'N' 		
	"/>
      </subReport>


      <subReport includeHeader="Db2Header" includeTotals="Y">
      	<SQL text="

		WITH TARGET_PERIOD(PERIOD_END_DTE) AS (
			SELECT MIN(PERIOD_END_DTE) FROM LENOVO.PERIOD_DATES WHERE LEN_DATA_REC = 'N' 
		),

		PARTS_CREDIT(KEY, PARTS_CREDIT) AS ( 
			SELECT 'PARTS', 
			VALUE(SUM(PART_CREDIT),0) AS PARTS_CREDIT 
			FROM LENOVO.PL_ALL_BYWW_V 
			WHERE EFFECTIVE_PERIOD IN (SELECT PERIOD_END_DTE FROM TARGET_PERIOD) 
			AND DETAIL_STATUS NOT IN ('CANCEL') 
			AND WW_CDE = '61' 
			AND COUNTRY_CDE = '649'
		),

		PARTS_WAC(KEY, PARTS_WAC) AS (
			SELECT 'PARTS', 
			VALUE(SUM(PART_COST), 0) AS PART_WAC
			FROM LENOVO.PL_ALL_BYWW_V 
			WHERE EFFECTIVE_PERIOD IN (SELECT PERIOD_END_DTE FROM TARGET_PERIOD) 
			AND DETAIL_STATUS NOT IN ('CANCEL') 
			AND WW_CDE = '60'
			AND COUNTRY_CDE = '649'
		),

		PARTS_SCRAP(KEY, PARTS_SCRAP) AS (
			SELECT 'PARTS', 
			VALUE(SUM(PART_COST), 0) AS PART_SCRAP
			FROM LENOVO.PL_ALL_BYWW_V 
			WHERE EFFECTIVE_PERIOD IN (SELECT PERIOD_END_DTE FROM TARGET_PERIOD) 
			AND DETAIL_STATUS NOT IN ('CANCEL') 
			AND WW_CDE IN ('48','49')
			AND COUNTRY_CDE = '649'
		),
		
		PARTS_ISC(KEY, PARTS_ISC) AS (
			SELECT 'PARTS', 
			VALUE(SUM(PART_COST), 0) AS PART_ISC
			FROM LENOVO.PL_ALL_BYWW_V 
			WHERE EFFECTIVE_PERIOD IN (SELECT PERIOD_END_DTE FROM TARGET_PERIOD) 
			AND DETAIL_STATUS NOT IN ('CANCEL') 
			AND WW_CDE IN ('99')
			AND COUNTRY_CDE = '649'
		),

		PARTS_OTHER(KEY, PARTS_OTHER) AS (
			SELECT 'PARTS', 
			VALUE(SUM(PART_COST), 0) AS PARTS_OTHER
			FROM LENOVO.PL_ALL_BYWW_V 
			WHERE EFFECTIVE_PERIOD IN (SELECT PERIOD_END_DTE FROM TARGET_PERIOD) 
			AND DETAIL_STATUS NOT IN ('CANCEL') 
			AND WW_CDE NOT IN ('61', '60', '48', '49', '99')
			AND COUNTRY_CDE = '649'
		),

		PARTS_FEE(KEY, PARTS_FEE) AS (
			SELECT 'PARTS', 
			VALUE(PARTS_WAC * .023, 0) AS PARTS_FEE
			FROM PARTS_WAC
		),
		
		PARTS_DIST(KEY, PARTS_DIST) AS (
			SELECT 'PARTS', 
			VALUE(SUM(BILLING_RATE * TRANSACTION_CNT), 0) AS PARTS_DIST
			FROM LENOVO.PL_ALL_BYWW_V 
			WHERE EFFECTIVE_PERIOD IN (SELECT PERIOD_END_DTE FROM TARGET_PERIOD) 
			AND DETAIL_STATUS NOT IN ('CANCEL') 
			AND WW_CDE NOT IN ('61', '60', '48', '49', '99')
			AND COUNTRY_CDE = '649'
		),

		PARTS_DIST_CR (KEY, PARTS_DIST_CR) AS (
			SELECT 'PARTS', 
			VALUE(SUM(BILLING_RATE * TRANSACTION_CNT), 0) AS PARTS_DIST_CR
			FROM LENOVO.PL_DETAIL_CR 
			WHERE PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM TARGET_PERIOD) 
			AND STATUS = 'CREDIT' 
                        AND BILLABLE = 'Y'
			AND WW_CDE NOT IN ('61', '60', '48', '49')
			AND COUNTRY_CDE = '649'
		),

		PARTS_COST_CR (KEY, PARTS_COST_CR) AS (
			SELECT 'PARTS', 
			VALUE(SUM(PART_COST), 0) AS PARTS_COST_CR
			FROM LENOVO.PL_DETAIL_CR 
			WHERE PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM TARGET_PERIOD) 
			AND STATUS = 'CREDIT' 
                        AND BILLABLE = 'Y'
			AND COUNTRY_CDE = '649'
		),

		BF(KEY, TOTAL_BF) AS (
			SELECT 'BREAK FIX',
			SUM(BILLING_RATE * TRANSACTION_CNT) AS TOTAL_BF
			FROM LENOVO.BF_ALL_BYWW_V A
			WHERE EFFECTIVE_PERIOD IN (SELECT PERIOD_END_DTE FROM TARGET_PERIOD) 
			AND DETAIL_STATUS NOT IN ('CANCEL')
			AND COUNTRY_CDE = '649'
		),

		BF_CR(KEY, TOTAL_BF_CR) AS (
			SELECT 'BREAK FIX',
			SUM(BILLING_RATE * TRANSACTION_CNT) AS TOTAL_BF_CR
			FROM LENOVO.BF_DETAIL_CR
			WHERE PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM TARGET_PERIOD) 
			AND STATUS = 'CREDIT' 
			AND BILLABLE = 'Y'
			AND COUNTRY_CDE = '649'
		),

		RCS(KEY, TOTAL_RCS) AS (
			SELECT 'RCS',
			SUM(BILLING_RATE * TRANSACTION_CNT) AS TOTAL_RCS
			FROM LENOVO.RCS_ALL_BYWW_V A
			WHERE EFFECTIVE_PERIOD IN (SELECT PERIOD_END_DTE FROM TARGET_PERIOD) 
			AND DETAIL_STATUS NOT IN ('CANCEL')
			AND COUNTRY_CDE = '649'
		),

		RCS_CR(KEY, TOTAL_RCS_CR) AS (
			SELECT 'RCS',
			SUM(BILLING_RATE * TRANSACTION_CNT) AS TOTAL_RCS_CR
			FROM LENOVO.RCS_DETAIL_CR
			WHERE PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM TARGET_PERIOD) 
			AND STATUS = 'CREDIT' 
			AND BILLABLE = 'Y'
			AND COUNTRY_CDE = '649'
		),

		DR(KEY, TOTAL_DR) AS (
			SELECT 'DEPOT',
			SUM(BILLING_RATE * TRANSACTION_CNT) AS TOTAL_DR
			FROM LENOVO.DR_ALL_BYWW_V A
			WHERE EFFECTIVE_PERIOD IN (SELECT PERIOD_END_DTE FROM TARGET_PERIOD) 
			AND DETAIL_STATUS NOT IN ('CANCEL')
			AND COUNTRY_CDE = '649'
		),

		DR_CR(KEY, TOTAL_DR_CR) AS (
			SELECT 'DEPOT',
			SUM(BILLING_RATE * TRANSACTION_CNT) AS TOTAL_DR_CR
			FROM LENOVO.DR_DETAIL_CR
			WHERE PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM TARGET_PERIOD) 
			AND STATUS = 'CREDIT' 
			AND BILLABLE = 'Y'
			AND COUNTRY_CDE = '649'
		),

		TOTAL_ALL (BUSINESS_AREA, TRANSACTIONS, PART_COST, PARTS_MANAGEMENT_FEE, SCRAP, TOTALS) AS (
			SELECT 'RCS' as BUSINESS_AREA, 
				ROUND(VALUE(TOTAL_RCS, 0) - VALUE(TOTAL_RCS_CR, 0), 2) AS TRANSACTIONS,
				0.00 AS PART_COST,
				0.00 AS PARTS_MANAGEMENT_FEE,
				0.00 AS SCRAP,
				ROUND(VALUE(TOTAL_RCS, 0) - VALUE(TOTAL_RCS_CR, 0), 2) AS TOTALS
			FROM RCS A LEFT JOIN RCS_CR B ON A .KEY = B.KEY 
			UNION all
			SELECT 'BF' as BUSINESS_AREA, 
				ROUND(VALUE(TOTAL_BF, 0) - VALUE(TOTAL_BF_CR, 0), 2) AS TRANSACTIONS,
				0 AS PART_COST,
				0 AS PARTS_MANAGEMENT_FEE,
				0 AS SCRAP,
				ROUND(VALUE(TOTAL_BF, 0) - VALUE(TOTAL_BF_CR, 0), 2) AS TOTALS
			FROM BF A LEFT JOIN BF_CR B ON A .KEY = B.KEY 
			UNION all
			SELECT 'DR' as BUSINESS_AREA, 
				ROUND(VALUE(TOTAL_DR, 0) - VALUE(TOTAL_DR_CR, 0), 2) AS TRANSACTIONS, 
				0 AS PART_COST,
				0 AS PARTS_MANAGEMENT_FEE,
				0 AS SCRAP,
				ROUND(VALUE(TOTAL_DR, 0) - VALUE(TOTAL_DR_CR, 0), 2) AS TOTALS
			FROM DR A LEFT JOIN DR_CR B ON A .KEY = B.KEY 
			UNION all
			SELECT 'PARTS  LOGISTICS' as BUSINESS_AREA, 
				ROUND(VALUE(PARTS_DIST, 0) - VALUE(PARTS_DIST_CR, 0) + VALUE(PARTS_ISC, 0) , 2) AS TRANSACTIONS,
				ROUND(VALUE(PARTS_WAC, 0) + VALUE(PARTS_OTHER, 0) - VALUE(PARTS_CREDIT, 0) - VALUE(PARTS_COST_CR, 0), 2) AS PART_COST,
				ROUND(VALUE(PARTS_FEE, 0), 2) AS PARTS_MANAGEMENT_FEE,
				ROUND(VALUE(PARTS_SCRAP, 0), 2) AS SCRAP,
				ROUND(VALUE(PARTS_WAC, 0) + VALUE(PARTS_OTHER, 0) + VALUE(PARTS_DIST, 0) + VALUE(PARTS_SCRAP, 0) + VALUE(PARTS_FEE, 0) - VALUE(PARTS_CREDIT, 0) - VALUE(PARTS_DIST_CR, 0) + VALUE(PARTS_ISC, 0) - VALUE(PARTS_COST_CR, 0) , 2) AS TOTALS
			FROM PARTS_WAC A LEFT JOIN PARTS_CREDIT B ON A .KEY = B.KEY 
			LEFT JOIN PARTS_FEE C ON A.KEY = C.KEY
			LEFT JOIN PARTS_DIST D ON A .KEY = D.KEY
			LEFT JOIN PARTS_SCRAP E ON A.KEY = E.KEY
			LEFT JOIN PARTS_OTHER F ON A.KEY = F.KEY
                        LEFT JOIN PARTS_DIST_CR G ON A .KEY = G.KEY
                        LEFT JOIN PARTS_ISC H ON A .KEY = H.KEY
                        LEFT JOIN PARTS_COST_CR I ON A .KEY = I.KEY
                        
		)

		SELECT * FROM TOTAL_ALL	
	"/>
      </subReport>
      
  </multiReport>    

</reports>

=== GitHubRepoForGTS/RepoForLSRFeed/LSR Feed/file_io/lsr_extract/xml_reports/lcbo_web.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--    INVOICE VALIDATION REPORT.  THIS REPORT COMPARES THE TOTAL THAT IBM WILL INVOICE LENOVO  -->
<!--    WITH THE TOTAL THAT LENOVO IS EXPECTING IBM TO INVOICE  -->

<!-- Modification History                            	 		-->
<!-- 2012-07-12 | VM | First Cut                                        -->


<!DOCTYPE reports SYSTEM "./../../dtd/LSRExtract.dtd">

<reports>
 
	<report includeHeader="Db2Header">
	<fileName text="report_summary_ts_lcbo_inv" delimiter="|"/>
	<dateFormat text="yyyy-mm-dd" />
	<timeFormat text="HH:MM:SS" />

	<SQL text="
		SELECT 
		'ts_lcbo_inv' AS &quot;project&quot;,
		'TS_LCBO' AS &quot;contract&quot;,
		'10000' AS &quot;summary_id&quot;,
		'N' AS &quot;requires_approval&quot;,
		'N' AS &quot;detail_page&quot;,
		STORE AS &quot;*store&quot;, 
		MACH AS &quot;*mach&quot;, 
		SERIAL AS &quot;*serial&quot;, 
		MODEL AS &quot;*model&quot;, 
		DESCRIPTION AS &quot;*description&quot;, 
		WARRANTY_EXP_DATE AS &quot;warranty_exp_date&quot;, 
		MA_START_DATE AS &quot;ma_start_date&quot;, 
		MA_END_DATE AS &quot;ma_end_date&quot;, 
		TAG AS &quot;tag&quot;, 
		DEVICE_TYPE AS &quot;device_type&quot;, 
		STATUS AS &quot;status&quot;, 
		PURCHASE_DATE AS &quot;purchase_date&quot;, 
		CALL_NUMBER AS &quot;call_number&quot;, 
		CALL_COMPLETION AS &quot;call_completion&quot;
		FROM LCBO.INVENTORY  	
	"/>
	</report>

	<report includeHeader="None">
	<fileName text="report_details_ts_lcbo_inv" delimiter="|"/>
	<dateFormat text="yyyy-mm-dd" />
	<timeFormat text="HH:MM:SS" />

	<SQL text="
		VALUES('summary_id|record_type|Quantity|Description|Upgrade|FRU|Price|')
	"/>
	</report>
	
	<report includeHeader="None">
	<fileName text="user_mapping" delimiter="|"/>
	<dateFormat text="yyyy-mm-dd" />
	<timeFormat text="HH:MM:SS" />

	<SQL text="
		VALUES('zzzts_lcbo_inv@gcsc.ibm.com|ts_lcbo_inv|TS_LCBO|')
	"/>
	</report>

</reports>

=== GitHubRepoForGTS/RepoForLSRFeed/LSR Feed/src/file_io/lsr_extract/xml_reports/Temp_Approved-Rejectedcycle2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--                                                 -->
<!--    Break-fix - Report SQLs DTD and XML          -->
<!--                                                 -->

<!-- Modification History                            	 		-->
<!-- 01/06/2005 | KW | First Cut					-->
<!-- 01/09/2005 | KW | Moved DTD to external file LSRExtract.dtd	-->


<!DOCTYPE reports SYSTEM "./../../dtd/LSRExtract.dtd">

<reports>

  <!-- Simulated Rejected Transactions -->

  <report includeHeader="Custom">
    <fileName text="CA_cycle2_rejected_onsitebfservice.csv" />
    <dateFormat text="YYYY/MM/DD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
	SELECT 	MACH,SERIAL,LLI,PERIOD_END_DTE,SERVICE_DTE,DOCNUM,ECA,POSTAL_CDE,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,'88888888' AS LENOVO_KEY,TRANSACTION_ID,CAST(99 AS INTEGER) AS REJECT_CDE
	FROM LENOVO.BF_BILLABLE_V 
	WHERE (PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE) AND MONTH = MONTH(CURRENT DATE)))
	AND (mod(cast(reject_id as integer),2) = 1)
    " />
  </report>

  <report includeHeader="Custom">
    <fileName text="CA_cycle2_rejected_depotrepair.csv" />
    <dateFormat text="YYYY/MM/DD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
	SELECT 	MACH,SERIAL,LLI,PERIOD_END_DTE,DOCNUM,ECA,POSTAL_CDE,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,'88888888' AS LENOVO_KEY,TRANSACTION_ID,CAST(99 AS INTEGER) AS REJECT_CDE
	FROM LENOVO.DR_BILLABLE_V 
	WHERE (PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE) AND MONTH = MONTH(CURRENT DATE)))
	AND (mod(cast(reject_id as integer),2) = 1)
    " />
  </report>

  <report includeHeader="Custom">
    <fileName text="CA_cycle2_rejected_installation.csv" />
    <dateFormat text="YYYY/MM/DD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
    	SELECT 	MACH,SERIAL,LLI,PERIOD_END_DTE,SERVICE_DTE,DOCNUM,POSTAL_CDE,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,'88888888' AS LENOVO_KEY,TRANSACTION_ID,CAST(99 AS INTEGER) AS REJECT_CDE
    	FROM LENOVO.INS_BILLABLE_V 
    	WHERE (PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE) AND MONTH = MONTH(CURRENT DATE)))
    	AND (mod(cast(reject_id as integer),2) = 1)
    " />
  </report>

  <report includeHeader="Custom">
    <fileName text="CA_cycle2_rejected_partslogistics.csv" />
    <dateFormat text="YYYY/MM/DD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
    	SELECT 	MACH,LLI,PERIOD_END_DTE,SHIP_DTE,DOCNUM,CLAIM_NUM,PARTNO,PARTQTY,PART_COST,DIST_COST,PART_CREDIT,POSTAL_CDE,ORDER_NUM,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,'88888888' AS LENOVO_KEY,TRANSACTION_ID,SERIAL,CAST(99 AS INTEGER) AS REJECT_CDE
	FROM LENOVO.PL_BILLABLE_V 
	WHERE (PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE) AND MONTH = MONTH(CURRENT DATE)))
	AND (mod(cast(reject_id as integer),2) = 1)
    " />
  </report>

  <report includeHeader="Custom">
    <fileName text="CA_cycle2_rejected_remotecustsupport.csv" />
    <dateFormat text="YYYY/MM/DD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
	SELECT 	MACH,SERIAL,LLI,PERIOD_END_DTE,DOCNUM,POSTAL_CDE,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,'88888888' AS LENOVO_KEY,TRANSACTION_ID,CAST(99 AS INTEGER) AS REJECT_CDE
	FROM LENOVO.RCS_BILLABLE_V 
	WHERE (PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE) AND MONTH = MONTH(CURRENT DATE)))
	AND (mod(cast(reject_id as integer),2) = 1)
    " />
  </report>



<!-- Simulated Approved Transactions -->

  <report includeHeader="Custom">
    <fileName text="invoice_cycle2_detail_onsitebfservice_CA.csv" />
    <dateFormat text="YYYY/MM/DD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
	SELECT 	MACH,SERIAL,LLI,PERIOD_END_DTE,SERVICE_DTE,DOCNUM,ECA,POSTAL_CDE,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,TRANSACTION_ID
	FROM LENOVO.BF_BILLABLE_V 
	WHERE (PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE) AND MONTH = MONTH(CURRENT DATE)))
	AND (mod(cast(reject_id as integer),2) = 0)
    " />
  </report>

  <report includeHeader="Custom">
    <fileName text="invoice_cycle2_detail_depotrepair_CA.csv" />
    <dateFormat text="YYYY/MM/DD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
	SELECT 	MACH,SERIAL,LLI,PERIOD_END_DTE,DOCNUM,ECA,POSTAL_CDE,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,TRANSACTION_ID
	FROM LENOVO.DR_BILLABLE_V 
	WHERE (PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE) AND MONTH = MONTH(CURRENT DATE)))
	AND (mod(cast(reject_id as integer),2) = 0)
    " />
  </report>

  <report includeHeader="Custom">
    <fileName text="invoice_cycle2_detail_installation_CA.csv" />
    <dateFormat text="YYYY/MM/DD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
    	SELECT 	MACH,SERIAL,LLI,PERIOD_END_DTE,SERVICE_DTE,DOCNUM,POSTAL_CDE,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,TRANSACTION_ID
    	FROM LENOVO.INS_BILLABLE_V 
    	WHERE (PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE) AND MONTH = MONTH(CURRENT DATE)))
    	AND (mod(cast(reject_id as integer),2) = 0)
    " />
  </report>

  <report includeHeader="Custom">
    <fileName text="invoice_cycle2_detail_partslogistics_CA.csv" />
    <dateFormat text="YYYY/MM/DD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
    	SELECT 	MACH,LLI,PERIOD_END_DTE,SHIP_DTE,DOCNUM,CLAIM_NUM,PARTNO,PARTQTY,PART_COST,DIST_COST,PART_CREDIT,POSTAL_CDE,ORDER_NUM,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,TRANSACTION_ID,SERIAL
	FROM LENOVO.PL_BILLABLE_V 
	WHERE (PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE) AND MONTH = MONTH(CURRENT DATE)))
	AND (mod(cast(reject_id as integer),2) = 0)
    " />
  </report>

  <report includeHeader="Custom">
    <fileName text="invoice_cycle2_detail_remotecustsupport_CA.csv" />
    <dateFormat text="YYYY/MM/DD" />
    <timeFormat text="HH:MM:SS" />
    <SQL text="
	SELECT 	MACH,SERIAL,LLI,PERIOD_END_DTE,DOCNUM,POSTAL_CDE,COUNTRY_CDE,WW_CDE,CASE WHEN STATUS = 'NEW' THEN 'N' WHEN STATUS = 'RESUBMIT' THEN 'R' END AS RESUBMIT_IND,TRANSACTION_ID
	FROM LENOVO.RCS_BILLABLE_V 
	WHERE (PERIOD_END_DTE IN (SELECT PERIOD_END_DTE FROM LENOVO.PERIOD_DATES WHERE YEAR = YEAR(CURRENT DATE) AND MONTH = MONTH(CURRENT DATE)))
	AND (mod(cast(reject_id as integer),2) = 0)
    " />
  </report>



</reports>
