=== GitHubRepoForGTS/RepoForLSRFeed/LSR Feed/src/file_io/dtd/LSRFeed.dtd
<!-- DTD (Document Type Definition) file to validate all LSRFeed XMLs:	-->
<!--     new_transaction_map.xml					-->
<!--     approved_map.xml						-->
<!--     rejected_map.xml						-->
<!--     resubmit_map.xml						-->
<!-- The above xml files are used in these Lenovo business lines:	-->
<!--     break-fix			(bf)				-->
<!--     depot repair			(dr)				-->
<!--	 install			(ins)				-->
<!--	 parts logistics 		(pl)				-->
<!--	 remote customer support 	(rcs)				-->

<!-- Modification History                                              	-->
<!-- 01/09/2005 | KW | First Cut					-->
<!-- 03/28/2006 | VM | C2246 Added new validation feature notEQValue which is a         -->
<!--                   new implied attribute of the dataType element                    -->
<!-- 03/28/2011 | MM | C4327 modify the LSR Feed tool to allow data in DB2 TIME and TIMESTAMP format to be inserted.-->
<!--                   dataType name="TIME" timeFormat="hh:mm:ss a"  dataType name="TIMESTAMP" timestampFormat="yyyy-mm-dd hh:mm:ss.fffffffff"  -->

<!-- CSV element: contains 1 targetTable element and >=1 column element -->
<!ELEMENT CSV (targetTable,column+)>

	<!-- Optional fileNameMustContain attribute verifies CSV filename contains the phrase expected by the business transaction folder containing it -->
	<!-- (e.g., in case an 'approved' csv file is placed in a 'rejected' transaction folder by mistake) -->
        <!ATTLIST CSV fileNameMustContain CDATA #IMPLIED>        
	<!-- targetTable is an empty element (no enclosed text) -->
	<!-- Its name attribute contains any character data -->
	<!ELEMENT targetTable EMPTY>
	
		<!ATTLIST targetTable name CDATA #REQUIRED>

	<!-- db2ColName, CSVMapTo, CSVIndex can appear at most once, if at all, in the column element. -->
	<!-- dataType must appear once in column element. --> 
	<!ELEMENT column (db2ColName?,CSVMapTo?,CSVIndex?,dataType) >

		<!ELEMENT db2ColName EMPTY > 
		
			<!ATTLIST db2ColName name ID #IMPLIED >

		<!ELEMENT CSVMapTo EMPTY >

			<!ATTLIST CSVMapTo name CDATA #IMPLIED >

		<!ELEMENT CSVIndex EMPTY >

			<!ATTLIST CSVIndex number CDATA #IMPLIED 
					   name CDATA #IMPLIED>

		<!-- dataType name attribute is mandatory and can be String/Date/Integer/Decimal -->
		<!-- maxLength, dateFormat,timeFormat,timestampFormat minValue, maxValue attributes are optional -->
		<!ELEMENT dataType EMPTY >

			<!ATTLIST dataType name (String | Date | Time | Timestamp | Integer | Decimal) #REQUIRED
				  maxLength CDATA #IMPLIED
				  dateFormat CDATA #IMPLIED
          timeFormat CDATA #IMPLIED
          timestampFormat CDATA #IMPLIED
				  minValue CDATA #IMPLIED
				  maxValue CDATA #IMPLIED
				  notEqValue CDATA #IMPLIED>

=== GitHubRepoForGTS/RepoForLSRFeed/LSR Feed/src/file_io/lsr_feed/depot_repair/xml_map/new_transaction_map.xml
<?xml version="1.0" encoding="UTF-8"?><!--                                                 --><!--    Depot Repair - New Transaction DTD and XML   --><!--                                                 --><!-- Modification History                                                			--><!-- 01/06/2005 | KW | Added fileNameMustContain attribute to CSV element in DTD		--><!--                   Changed LENA_CASE maxLength from 7 to 8                  		--><!--                   Changed SERIAL CSVMapTo from MACHINE SERIAL to DR SERIAL 		--><!--                   (distinct name helps detect when csv is put in wrong business folder)	--><!-- 01/09/2005 | KW | Moved DTD to external file LSRFeed.dtd					--><!-- 03/28/2006 | VM | C2246 Changed validation maxlength from 5 to 20 for BP_ID & ORIGINAL_BP_ID   --><!--                   C2246 Changed validation to -1, 0, 1 only for TRANSACTION_CNT                --><!-- 11/14/2009 | VM | V21  Removed LENA_CASE WESSN_DOCNUM WESSN_DOCNUM_DTE BP_ID ORIGINAL_BP_ID  -->

<!DOCTYPE CSV SYSTEM "./../../../dtd/LSRFeed.dtd"><CSV>  <targetTable name="LENOVO.DR_DETAIL" />
  <column>    <db2ColName name="MACH" />    <CSVMapTo name="MACHINE TYPE" />    <dataType name="String" maxLength="4" />  </column>
  <column>    <db2ColName name="SERIAL" />    <CSVMapTo name="DR SERIAL" />    <dataType name="String" maxLength="25" />  </column>
  <column>    <db2ColName name="LLI" />    <CSVMapTo name="LLI" />    <dataType name="String" maxLength="3" />  </column>
  <column>    <db2ColName name="DOCNUM" />    <CSVMapTo name="PROBLEM NUMBER" />    <dataType name="String" maxLength="9" />  </column>
  <column>    <db2ColName name="ECA" />    <CSVMapTo name="ECA" />    <dataType name="String" maxLength="3" />  </column>
  <column>    <db2ColName name="POSTAL_CDE" />    <CSVMapTo name="POSTAL CODE" />    <dataType name="String" maxLength="7" />  </column>
  <column>    <db2ColName name="COUNTRY_CDE" />    <CSVMapTo name="COUNTRY CODE" />    <dataType name="String" maxLength="3" />  </column>
  <column>    <db2ColName name="WW_CDE" />    <CSVMapTo name="WW CODE" />    <dataType name="String" maxLength="2" />  </column>
  <column>    <db2ColName name="SDW_COMP_ID" />    <CSVMapTo name="SDW COMPONENT" />    <dataType name="String" maxLength="8" />  </column>
  <column>    <db2ColName name="US_BILL_DESC" />    <CSVMapTo name="US GROUP" />    <dataType name="String" maxLength="75" />  </column>
  <column>    <db2ColName name="CDN_BILL_DESC" />    <CSVMapTo name="BILLING DESCR" />    <dataType name="String" maxLength="75" />  </column>
  <column>    <db2ColName name="TRANSACTION_CNT" />    <CSVMapTo name="TRANSACTION COUNT" />    <dataType name="Integer" minValue="-1" maxValue="1" notEqValue="0" />  </column>
  <column>    <db2ColName name="PROVINCE_NAME" />    <CSVMapTo name="PROVINCE" />    <dataType name="String" maxLength="25" />  </column>
  <column>    <db2ColName name="SERV_PERFORMED_DTE" />    <CSVMapTo name="SERV PERFORMED DATE" />    <dataType name="Date" dateFormat="YYYY/MM/DD" />  </column>
  <column>    <db2ColName name="DATA_SOURCE" />    <CSVMapTo name="DATA SOURCE" />    <dataType name="String" maxLength="2" />  </column>
  <column>    <db2ColName name="BILLING_RATE" />    <CSVMapTo name="BILLING RATE" />    <dataType name="Decimal" minValue="0.0" maxValue="1000000.0" />  </column>
</CSV>

=== GitHubRepoForGTS/RepoForLSRFeed/LSR Feed/src/file_io/lsr_feed/cost_recovery_hs/xml_map/new_transaction_map.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--                                                 --><!--    Cost Recovery - New Transaction DTD and XML      --><!--                                                 --><!-- Modification History                                                			--><!-- 02/14/2012 | MM | init		-->
<!DOCTYPE CSV SYSTEM "./../../../dtd/LSRFeed.dtd"><CSV>  <targetTable name="COST.COST_RECOVERY_HS" />
  <column>    <db2ColName name="SECTION" />    <CSVMapTo name="SECTION" />    <dataType name="String" maxLength="20" />  </column>
  <column>    <db2ColName name="DOCNUM" />    <CSVMapTo name="DOCNUM" />    <dataType name="String" maxLength="20" />  </column>
  <column>    <db2ColName name="INQPERIOD" />    <CSVMapTo name="INQPERIOD" />    <dataType name="String" maxLength="6" />  </column>
  <column>    <db2ColName name="CALL_NUM" />    <CSVMapTo name="CALL_NUM" />    <dataType name="String" maxLength="20"  />  </column>
  <column>    <db2ColName name="MACH" />    <CSVMapTo name="MACH" />    <dataType name="String" maxLength="4" />  </column>  <column>    <db2ColName name="SERIAL" />    <CSVMapTo name="SERIAL" />    <dataType name="String" maxLength="20" />  </column>
  <column>    <db2ColName name="CS_STATUS" />    <CSVMapTo name="CS_STATUS" />    <dataType name="String" maxLength="10" />  </column>
  <column>    <db2ColName name="CS_BUS_SEG_CDE" />    <CSVMapTo name="CS_BUS_SEG_CDE" />    <dataType name="String" maxLength="10" />  </column>
  <column>    <db2ColName name="CS_PROD_OWN_CDE" />    <CSVMapTo name="CS_PROD_OWN_CDE" />    <dataType name="String" maxLength="10" />  </column>  <column>    <db2ColName name="SERVCODE" />    <CSVMapTo name="SERVCODE" />    <dataType name="String" maxLength="10" />  </column>
  <column>    <db2ColName name="RATE_PRIORTY" />    <CSVMapTo name="RATE_PRIORTY" />    <dataType name="String" maxLength="10" />  </column>  <column>    <db2ColName name="DELIVERY" />    <CSVMapTo name="DELIVERY" />    <dataType name="String" maxLength="20" />  </column>
  <column>    <db2ColName name="DELIVERY_LEVEL" />    <CSVMapTo name="DELIVERY_LEVEL" />    <dataType name="String" maxLength="20" />  </column>
  <column>    <db2ColName name="SERV_TERR" />    <CSVMapTo name="SERV_TERR" />    <dataType name="String" maxLength="10" />  </column>  <column>    <db2ColName name="UNKNOWN_MACH" />    <CSVMapTo name="UNKNOWN_MACH" />    <dataType name="Integer"  />  </column>
<column>
    <db2ColName name="SHIP_DATE" />
    <CSVMapTo name="SHIP_DATE" />
    <dataType name="Date" dateFormat="YYYY/MM/DD" />
  </column>
  
  <column>
      <db2ColName name="WARRANTY_END" />
      <CSVMapTo name="WARRANTY_END" />
      <dataType name="Date" dateFormat="YYYY/MM/DD" />
  </column>
  
  <column>
      <db2ColName name="LENOVO_FLAG" />
      <CSVMapTo name="LENOVO_FLAG" />
      <dataType name="Integer"  />
  </column>
 <column>
    <db2ColName name="TOTAL_HRS" />
    <CSVMapTo name="TOTAL_HRS" />
    <dataType name="Decimal" />
  </column>
  <column>
      <db2ColName name="PART_ROWS" />
      <CSVMapTo name="PART_ROWS" />
      <dataType name="Decimal" />
  </column>
  <column>
      <db2ColName name="LABOUR_COST" />
      <CSVMapTo name="LABOUR_COST" />
      <dataType name="Decimal" />
  </column>
  <column>
      <db2ColName name="PART_COST" />
      <CSVMapTo name="PART_COST" />
      <dataType name="Decimal" />
  </column>
  <column>
      <db2ColName name="DISTRIBUTION_COST" />
      <CSVMapTo name="DISTRIBUTION_COST" />
      <dataType name="Decimal" />
  </column>
   <column>
        <db2ColName name="PROVISION_COST" />
        <CSVMapTo name="PROVISION_COST" />
        <dataType name="Decimal" />
  </column>
   <column>
        <db2ColName name="TOTAL_COST" />
        <CSVMapTo name="TOTAL_COST" />
        <dataType name="Decimal" />
  </column>
</CSV>

=== GitHubRepoForGTS/RepoForLSRFeed/LSR Feed/src/file_io/lsr_feed/install/xml_map/new_transaction_map.xml
<?xml version="1.0" encoding="UTF-8"?><!--                                                 --><!--    Install - New Transaction DTD and XML        --><!--                                                 --><!-- Modification History                                                			--><!-- 01/06/2005 | KW | Added fileNameMustContain attribute to CSV element in DTD		--><!--                   Changed LENA_CASE maxLength from 7 to 8                  		--><!--                   Changed SERIAL CSVMapTo from MACHINE SERIAL to INS SERIAL 		--><!--                   (distinct name helps detect when csv is put in wrong business folder)	--><!-- 01/09/2005 | KW | Moved DTD to external file LSRFeed.dtd					--><!-- 03/28/2006 | VM | C2246 Changed validation maxlength from 5 to 20 for BP_ID & ORIGINAL_BP_ID   --><!--                   C2246 Changed validation to -1, 0, 1 only for TRANSACTION_CNT                --><!-- 11/14/2009 | VM | V21  Removed LENA_CASE WESSN_DOCNUM WESSN_DOCNUM_DTE BP_ID ORIGINAL_BP_ID WW_CDE US_BILL_DESC CDN_BILL_DESC BILLING_RATE -->


<!DOCTYPE CSV SYSTEM "./../../../dtd/LSRFeed.dtd"><CSV>  <targetTable name="LENOVO.INS_DETAIL" />
  <column>    <db2ColName name="MACH" />    <CSVMapTo name="MACHINE TYPE" />    <dataType name="String" maxLength="4" />  </column>
  <column>    <db2ColName name="SERIAL" />    <CSVMapTo name="INS SERIAL" />    <dataType name="String" maxLength="25" />  </column>
  <column>    <db2ColName name="LLI" />    <CSVMapTo name="LLI" />    <dataType name="String" maxLength="3" />  </column>
  <column>    <db2ColName name="SERVICE_DTE" />    <CSVMapTo name="SERVICE DATE" />    <dataType name="Date" dateFormat="YYYY/MM/DD" />  </column>  <column>    <db2ColName name="DOCNUM" />    <CSVMapTo name="PROBLEM NUMBER" />    <dataType name="String" maxLength="9" />  </column>
  <column>    <db2ColName name="POSTAL_CDE" />    <CSVMapTo name="POSTAL CODE" />    <dataType name="String" maxLength="7" />  </column>
  <column>    <db2ColName name="COUNTRY_CDE" />    <CSVMapTo name="COUNTRY CODE" />    <dataType name="String" maxLength="3" />  </column>
  <column>    <db2ColName name="SDW_COMP_ID" />    <CSVMapTo name="SDW COMPONENT" />    <dataType name="String" maxLength="8" />  </column>  <column>    <db2ColName name="TRANSACTION_CNT" />    <CSVMapTo name="TRANSACTION COUNT" />    <dataType name="Integer" minValue="-1" maxValue="1" notEqValue="0" />  </column>
  <column>    <db2ColName name="PROVINCE_NAME" />    <CSVMapTo name="PROVINCE" />    <dataType name="String" maxLength="25" />  </column>
  <column>    <db2ColName name="SERV_PERFORMED_DTE" />    <CSVMapTo name="SERV PERFORMED DATE" />    <dataType name="Date" dateFormat="YYYY/MM/DD" />  </column>  <column>    <db2ColName name="NSS_CALL_NUM" />    <CSVMapTo name="NSS CALL NUM" />    <dataType name="String" maxLength="8" />  </column>  <column>    <db2ColName name="CALL_RECD_DTE" />    <CSVMapTo name="CALL RECD DATE" />    <dataType name="Date" dateFormat="YYYY/MM/DD" />  </column>
  <column>    <db2ColName name="DATA_SOURCE" />    <CSVMapTo name="DATA SOURCE" />    <dataType name="String" maxLength="2" />  </column>
</CSV>

=== GitHubRepoForGTS/RepoForLSRFeed/LSR Feed/src/file_io/lsr_feed/parts/xml_map/approved_map.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--                                                   -->
<!-- Part Logistics - Approved Transaction DTD and XML -->
<!--                                                   -->

<!-- Modification History                                                			-->
<!-- 01/06/2005 | KW | First Cut								-->
<!-- 01/09/2005 | KW | Moved DTD to external file LSRFeed.dtd					-->
<!-- 02/13/2007 | VM | Added PART COST and PART CREDIT columns that are read in			-->
<!-- 02/27/2007 | VM | Changed PART CREDIT column from 9 to 10                          	-->
<!-- 09/02/2008 | JWF| Changed Transaction_ID maxlength from 20 to 30                           -->
<!-- 09/02/2008 | JWF| Changed DOCNUM maxlength from 9 to 12                                    -->
<!-- 05/01/2009 | VM | Changed DOCNUM maxlength from 12 to 19                                   -->

<!DOCTYPE CSV SYSTEM "./../../../dtd/LSRFeed.dtd">

<CSV fileNameMustContain="invoice,accepted">
  <targetTable name="LENOVO.PL_DETAIL" />
  <column>
    <CSVIndex number="0" name="MACH" />
    <dataType name="String" maxLength="4" />
  </column>
  <column>
    <CSVIndex number="4" name="DOCNUM" />
    <dataType name="String" maxLength="19" />
  </column>
  <column>
    <CSVIndex number="17" name="SERIAL" />
    <dataType name="String" maxLength="25" />
  </column>
  <column>
    <CSVIndex number="13" name="COUNTRY_CDE" />
    <dataType name="String" maxLength="3" />
  </column>
  <column>
    <CSVIndex number="14" name="WW_CDE" />
    <dataType name="String" maxLength="2" />
  </column>
  <column>
    <CSVIndex number="16" name="TRANSACTION_ID" />
    <dataType name="String" maxLength="30" />
  </column>
  <column>
    <CSVIndex number="1" name="LLI" />
    <dataType name="String" maxLength="3" />
  </column>  
  <column>
    <CSVIndex number="8" name="PART_COST" />
    <dataType name="Decimal"/>
  </column>
  <column>
    <CSVIndex number="10" name="PART_CREDIT" />
    <dataType name="Decimal"/>
  </column>  
</CSV>

=== GitHubRepoForGTS/RepoForLSRFeed/LSR Feed/bin/file_io/lsr_feed/break_fix/xml_map/resubmit_map.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--                                                      -->
<!--    Break-fix - Resubmitted Transaction DTD and XML   -->
<!--                                                      -->

<!-- Modification History                                                			-->
<!-- 01/06/2005 | KW | First Cut								-->
<!-- 01/09/2005 | KW | Moved DTD to external file LSRFeed.dtd					-->


<!DOCTYPE CSV SYSTEM "./../../../dtd/LSRFeed.dtd">

<CSV>
  <targetTable name="LENOVO.BF_REJECT" />

  <!-- CSV columns used for updating DB2 -->
  <column>
    <db2ColName name="MACH" />
    <CSVMapTo name="MACH" />
    <dataType name="String" maxLength="4" />
  </column>
  <column>
    <db2ColName name="SERIAL" />
    <CSVMapTo name="SERIAL" />
    <dataType name="String" maxLength="25" />
  </column>
  <column>
    <db2ColName name="LLI" />
    <CSVMapTo name="LLI" />
    <dataType name="String" maxLength="3" />
  </column>
  <column>
    <db2ColName name="COUNTRY_CDE" />
    <CSVMapTo name="COUNTRY_CDE" />
    <dataType name="String" maxLength="3" />
  </column>
  <column>
    <db2ColName name="WW_CDE" />
    <CSVMapTo name="WW_CDE" />
    <dataType name="String" maxLength="2" />
  </column>  
  <column>
    <db2ColName name="COMMENTS" />
    <CSVMapTo name="COMMENTS" />
    <dataType name="String" maxLength="80" />
  </column>
  
  <!-- CSV columns used for read only -->
  <column>
    <CSVMapTo name="RESUBMIT_IND" />
    <dataType name="String" maxLength="3" />
  </column>
  <column>
    <CSVMapTo name="REJECT_ID" />
    <dataType name="String" maxLength="20" />
  </column>
</CSV>

=== GitHubRepoForGTS/RepoForLSRFeed/LSR Feed/bin/file_io/lsr_feed/break_fix/xml_map/approved_map.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--                                                   -->
<!--    Break-fix - Approved Transaction DTD and XML   -->
<!--                                                   -->

<!-- Modification History                                                			-->
<!-- 01/06/2005 | KW | Added fileNameMustContain attribute to CSV element in DTD and XML	-->
<!--                   Added text attribute to CSVIndex element in DTD and XML			-->
<!--                   Changed TRANSACTION_ID dataType from Integer to String with maxLength 20 -->
<!-- 01/09/2005 | KW | Moved DTD to external file LSRFeed.dtd					-->


<!DOCTYPE CSV SYSTEM "./../../../dtd/LSRFeed.dtd">

<CSV fileNameMustContain="invoice,accepted">
  <targetTable name="LENOVO.BF_DETAIL" />
  <column>
    <CSVIndex number="0" name="MACH" />
    <dataType name="String" maxLength="4" />
  </column>
  <column>
    <CSVIndex number="1" name="SERIAL" />
    <dataType name="String" maxLength="25" />
  </column>
  <column>
    <CSVIndex number="5" name="DOCNUM" />
    <dataType name="String" maxLength="9" />
  </column>
  <column>
    <CSVIndex number="8" name="COUNTRY_CDE" />
    <dataType name="String" maxLength="3" />
  </column>
  <column>
    <CSVIndex number="9" name="WW_CDE" />
    <dataType name="String" maxLength="2" />
  </column>
  <column>
    <CSVIndex number="11" name="TRANSACTION_ID" />
    <dataType name="String" maxLength="20" />
  </column>
  <column>
    <CSVIndex number="2" name="LLI" />
    <dataType name="String" maxLength="3" />
  </column>  
</CSV>

=== GitHubRepoForGTS/RepoForLSRFeed/LSR Feed/bin/file_io/lsr_feed/parts/xml_map/new_transaction_map.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--                                                 -->
<!--  Parts Logistics - New Transaction DTD and XML  -->
<!--                                                 -->

<!-- Modification History                                                			-->
<!-- 01/06/2005 | KW | Added fileNameMustContain attribute to CSV element in DTD		-->
<!--                   Changed LENA_CASE maxLength from 7 to 8                  		-->
<!--                   Changed SERIAL CSVMapTo from MACHINE SERIAL to PL SERIAL 		-->
<!--                   (distinct name helps detect when csv is put in wrong business folder)	-->
<!-- 01/09/2005 | KW | Moved DTD to external file LSRFeed.dtd					-->
<!-- 03/28/2006 | VM | C2246 Changed validation maxlength from 5 to 20 for BP_ID & ORIGINAL_BP_ID   -->
<!--                   C2246 Changed validation to -1, 0, 1 only for TRANSACTION_CNT                -->
<!-- 11/14/2009 | VM | V21  Removed LENA_CASE WESSN_DOCNUM WESSN_DOCNUM_DTE BP_ID ORIGINAL_BP_ID WW_CDE US_BILL_DESC CDN_BILL_DESC BILLING_RATE DIST_COST-->


<!DOCTYPE CSV SYSTEM "./../../../dtd/LSRFeed.dtd">

<CSV>
  <targetTable name="LENOVO.PL_DETAIL" />

  <column>
    <db2ColName name="MACH" />
    <CSVMapTo name="MACHINE TYPE" />
    <dataType name="String" maxLength="4" />
  </column>

  <column>
    <db2ColName name="LLI" />
    <CSVMapTo name="LLI" />
    <dataType name="String" maxLength="3" />
  </column>

  <column>
    <db2ColName name="SHIP_DTE" />
    <CSVMapTo name="SHIP DATE" />
    <dataType name="Date" dateFormat="YYYY/MM/DD" />
  </column>

  <column>
    <db2ColName name="DOCNUM" />
    <CSVMapTo name="PROBLEM NUMBER" />
    <dataType name="String" maxLength="9" />
  </column>

  <column>
    <db2ColName name="CLAIM_NUM" />
    <CSVMapTo name="CLAIM NUMBER" />
    <dataType name="String" maxLength="20" />
  </column>

  <column>
    <db2ColName name="PARTNO" />
    <CSVMapTo name="PART NUMBER" />
    <dataType name="String" maxLength="12" />
  </column>

  <column>
    <db2ColName name="PARTQTY" />
    <CSVMapTo name="PART QUANTITY" />
    <dataType name="Integer"/>
  </column>

  <column>
    <db2ColName name="PART_COST" />
    <CSVMapTo name="PART COST" />
    <dataType name="Decimal"/>
  </column>

  <column>
    <db2ColName name="PART_CREDIT" />
    <CSVMapTo name="PART CREDIT" />
    <dataType name="Decimal"/>
  </column>

  <column>
    <db2ColName name="POSTAL_CDE" />
    <CSVMapTo name="POSTAL CODE" />
    <dataType name="String" maxLength="7" />
  </column>

  <column>
    <db2ColName name="ORDER_NUM" />
    <CSVMapTo name="ORDER NUMBER" />
    <dataType name="String" maxLength="6" />
  </column>

  <column>
    <db2ColName name="COUNTRY_CDE" />
    <CSVMapTo name="COUNTRY CODE" />
    <dataType name="String" maxLength="3" />
  </column>

  <column>
    <db2ColName name="SDW_COMP_ID" />
    <CSVMapTo name="SDW COMPONENT" />
    <dataType name="String" maxLength="8" />
  </column>

  <column>
    <db2ColName name="TRANSACTION_CNT" />
    <CSVMapTo name="TRANSACTION COUNT" />
    <dataType name="Integer" minValue="-1" maxValue="1" notEqValue="0" />
  </column>

  <column>
    <db2ColName name="PROVINCE_NAME" />
    <CSVMapTo name="PROVINCE" />
    <dataType name="String" maxLength="25" />
  </column>

  <column>
    <db2ColName name="SERV_PERFORMED_DTE" />
    <CSVMapTo name="SERV PERFORMED DATE" />
    <dataType name="Date" dateFormat="YYYY/MM/DD" />
  </column>

  <column>
    <db2ColName name="NSS_CALL_NUM" />
    <CSVMapTo name="NSS CALL NUM" />
    <dataType name="String" maxLength="8" />
  </column>

  <column>
    <db2ColName name="CALL_RECD_DTE" />
    <CSVMapTo name="CALL RECD DATE" />
    <dataType name="Date" dateFormat="YYYY/MM/DD" />
  </column>

  <column>
    <db2ColName name="DATA_SOURCE" />
    <CSVMapTo name="DATA SOURCE" />
    <dataType name="String" maxLength="2" />
  </column>

  <column>
    <db2ColName name="ASN" />
    <CSVMapTo name="ASN" />
    <dataType name="String" maxLength="7" />
  </column>

  <column>
    <db2ColName name="JOB_NUMBER" />
    <CSVMapTo name="JOB NUMBER" />
    <dataType name="String" maxLength="8" />
  </column>

  <column>
    <db2ColName name="SERIAL" />
    <CSVMapTo name="PL SERIAL" />
    <dataType name="String" maxLength="25" />
  </column>

  <column>  
      <db2ColName name="P900_CODE" />  
      <CSVMapTo name="P900 CODE3" />
      <dataType name="String" maxLength="11" />
  </column>	

</CSV>
